server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/gym_crm
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: vital
    password: fhsjsk165_!hg


management:
  endpoint:
    health:
      show-components: when_authorized
  endpoints:
    web:
      exposure:
        include: prometheus

logging:
  level:
    root: DEBUG