spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym_crm
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12062003

management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    root: INFO